# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# remove bell sound
set-option -g bell-action none
set-option -g visual-bell on

# status line
set-option -g status on
set-option -g status-position bottom
set-option -g status-style fg=green,bg=default
set-option -g status-right "#(whoami) >> %b %d %Y @ %l:%M %p"
set -g status-interval 2
set -g status-justify left

# automatic window renaming
set-window-option -g automatic-rename on
setw -g automatic-rename

# visual notification of activity in other windows
set -g visual-activity on

# split panes using | and -
bind | split-window -h -c '#{pane_current_path}' # split vertically
bind - split-window -v -c '#{pane_current_path}' # split horizontally
unbind '"'
unbind %

# bind current path to new window
bind c new-window -c '#{pane_current_path}'

# reload config file
bind r source-file ~/.tmux.conf

# enable mouse mode (tmux 2.1+)
setw -g mouse on

# plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

# default terminal
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# set vim keybindings
setw -g mode-keys vi

# faster command sequences
# https://mutelight.org/practical-tmux#section-4
set -s escape-time 0

# aggressive resize
# https://mutelight.org/practical-tmux#section-5
set -g aggressive-resize on

# clipboard
set -g @override_copy_command 'xclip -sel clipboard'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# initialize tmux plugin manager
run -b '~/.tmux/plugins/tpm/tpm'
