# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c '#{pane_current_path}' # split vertically
bind - split-window -v -c '#{pane_current_path}' # split horizontally
unbind '"'
unbind %

# bind current path to new window
bind c new-window -c '#{pane_current_path}'

# reload config file
bind r source-file ~/.tmux.conf

# enable mouse mode (tmux 2.1+)
set -g mouse on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'christoomey/vim-tmux-navigator'

# theme
set -g @themepack 'powerline/default/green'

# default terminal
set-option -g default-terminal "screen-256color" 

# copy from tmux buffer to system buffer (clipboard)
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'

# initialize tmux plugin manager
run -b '~/.tmux/plugins/tpm/tpm'

