alias g "git"
alias gc "git commit"
alias gm "git merge"
alias gs "git status"
alias ga "git add"
alias gg "git grep"
alias gd "git diff"
alias gps "git push"
alias gpl "git pull"
alias gst "git stash"
alias gco "git checkout"
